### ISSUE TITLE
Aufgabe 01 Feedback

### ISSUE THREAD

**Issue by MarkusDamm** [Jonas915/eia2_SoSe20#1]
Hallo Jonas,
du bist lt. Steckbrief zwar nur für die Endabgabe auf der Kursseite angemeldet, hast aber eine Aufgabe abgegeben. Also ein kleines Feedback für dich:
Bitte verlinke dieses Repository im Steckbrief, wenn du noch weiter Aufgaben abgibst.
Bei deinem Aktivitätsdiagramm (AD) gibt's mehrere Formfehler, z.B. hast du [i++] durch die eckigen Klammern als eine Bedingung formuliert, obwohl es keine ist. Da, wo der Switch ist, hast du auch nicht geschrieben, wie die Bedingungen geprüft werden. Paar kleinere Sachen kommen noch dazu, leider fehlt aber auch das komplette AD zur createBox-Funktion, auf die du immerhin schon verwiesen hast.
Wenn ich auf weiteres eingehen soll, dann sag das gerne.
MfG Markus

**Comment by Jonas915** [comment]
Vielen Dank für das konstruktive Feedback!
Du hast Recht, den Switch und die createBox Funktion habe ich nicht korrekt angegeben. 
Ich denke aber, dass ich damit was anfangen kann und bin mir sicher, dass die nächsten ADs besser werden. Das Repository werde ich noch verlinken.
